name: CI

on: [push]

permissions: {}

jobs:
  bug:
    strategy:
      matrix:
        version: [
          2.2.2,
          2.2.1,
          2.2.0,
          2.1.10
          ]
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.version }}

      - name: Check
        run: |
          deno compile -o main main.ts &&
          ./main
